language: python
python:
     - "3.4"
     - "3.5"
     - "3.6"
install:
  - pip install -r src/python/national_voter_file/tests/requirements.txt
  - python setup.py install
script:
  - pylint --rcfile=.pylintrc src/python/national_voter_file/ -f parseable -r n
  - nosetests src/python/national_voter_file/tests
